#!/bin/sh

case "$1" in
    start)
        aesdchar_load
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        rmmod hello
        module_unload faulty
        sull_unload
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    
    exit 1
esac

exit 0
